# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort vsot
    types: [python]
    pass_filenames: false # In order to respect the ignore list


  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black vsot
    types: [python]
    pass_filenames: false # In order to respect the ignore list


  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8 vsot
    types: [python]
    pass_filenames: false # In order to respect the ignore list
